# This file contains configuration options for GolangCI-Lint.
#
# - It requires golangci-lint v1.52.0 or later.
# - Available linters see: https://golangci-lint.run/usage/linters/
# - Sample of config see: https://golangci-lint.run/usage/configuration/#config-file

# Options for analysis running
run:
  # Include test files.
  tests: true
  # Fail fast.
  fast: true

  # List of build tags, all linters use it. Default is empty list.
  build-tags:
    - golangci

  # Which dirs to skip. Issues from them won't be reported.
  skip-dirs:
    - .github

  # Allow multiple parallel golangci-lint instances running.
  allow-parallel-runners: true

# Output configuration options
output:
  format: colored-line-number

  # Sorts results by: filepath, line and column
  sort-results: true

# Enabled all linters. Conf settings may follow.
linters:
  enable-all: true
  disable:
  # Disable deprecated linters
  - exhaustivestruct
  - golint
  - ifshort
  - interfacer
  - maligned
  - scopelint
  - structcheck
  - varcheck
  - deadcode
  - nosnakecase
  # Disable due to testing private functions
  - testpackage
  # Disable due to using singletons and init functions
  - gochecknoinits
  - gochecknoglobals
linters-settings:
  depguard:
    rules:
      main:
        # List of allowed packages.
        allow:
          # Go standard library
          - $gostd
          # Required for hashsing
          - github.com/zeebo/blake3
          # Deprecated but required for simple error handling
          - github.com/pkg/errors
          # Required for testing
          - github.com/KEINOS/go-bayes
          - github.com/stretchr/testify
