# Details of this action see: https://github.com/golangci/golangci-lint-action
name: golangci-lint

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --config ./.golangci.yml
