name: unit-test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: unit-test
        run: go test -v ./...
