name: unit-test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  unit-test:
    name: unit-test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          # Due to our "fail-fast" policy, we use the latest Go to detect
          # compatibility breakage ASAP. Therefore, '1.x' is ok.
          go-version: '1.x'
          check-latest: true
      - name: unit-test
        run: go test -race -v ./... ./_examples/http_status ./_examples/iris ./_examples/melody ./_examples/mushroom ./_examples/wine
